"""
test_risk_scoring.py
======================
Unit tests for src/risk_scoring.py.

Uses the real Phase 3 serialized model artifacts (regenerated by the
synthetic-fixture pipeline) via `RiskScoringEngine`'s default disk-
loading path, plus a lightweight injected-pipeline path for tests that
need a controlled, fast model.

Run with:
    pytest tests/ -v
"""

import sys
import warnings
from pathlib import Path

import numpy as np
import pytest

warnings.filterwarnings("ignore")

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src import model_utils, utils  # noqa: E402
from src.configurable_thresholds import RiskThresholdConfig  # noqa: E402
from src.risk_scoring import RiskScoringEngine, expand_threshold_analysis, plot_expanded_threshold_analysis  # noqa: E402


@pytest.fixture(scope="module")
def splits():
    return utils.load_splits()


@pytest.fixture(scope="module")
def quick_pipeline(splits):
    """A cheaply-trained Logistic Regression pipeline for fast, isolated tests (avoids a full Phase 3 hyperparameter search)."""
    X_train, X_val, X_test, y_train, y_val, y_test = splits
    pipeline = model_utils.build_logistic_regression_pipeline()
    pipeline.fit(X_train, y_train)
    return pipeline


@pytest.fixture
def engine(quick_pipeline):
    return RiskScoringEngine(model_key="logistic_regression", pipeline=quick_pipeline)


# ---------------------------------------------------------------------------
# Construction
# ---------------------------------------------------------------------------


def test_engine_construction_with_injected_pipeline(quick_pipeline):
    engine = RiskScoringEngine(model_key="logistic_regression", pipeline=quick_pipeline)
    assert engine.model_key == "logistic_regression"
    assert 0.0 <= engine._decision_threshold <= 1.0


def test_engine_construction_invalid_model_key_raises(quick_pipeline):
    with pytest.raises(ValueError):
        RiskScoringEngine(model_key="not_a_real_model", pipeline=quick_pipeline)


# ---------------------------------------------------------------------------
# Core prediction
# ---------------------------------------------------------------------------


def test_predict_probability_shape_and_range(engine, splits):
    _, _, X_test, _, _, _ = splits
    proba = engine.predict_probability(X_test)
    assert len(proba) == len(X_test)
    assert (proba >= 0).all() and (proba <= 1).all()


def test_predict_uses_recommended_threshold_by_default(engine, splits):
    _, _, X_test, _, _, _ = splits
    predictions = engine.predict(X_test)
    proba = engine.predict_probability(X_test)
    expected = (proba >= engine._decision_threshold).astype(int)
    assert np.array_equal(predictions, expected)


def test_predict_with_explicit_threshold_override(engine, splits):
    _, _, X_test, _, _, _ = splits
    predictions = engine.predict(X_test, threshold=0.99)
    # Almost nothing should be flagged at a 0.99 cutoff.
    assert predictions.sum() <= 1


# ---------------------------------------------------------------------------
# Risk scoring
# ---------------------------------------------------------------------------


def test_calculate_risk_score_scales_correctly(engine):
    assert engine.calculate_risk_score(0.0) == 0.0
    assert engine.calculate_risk_score(1.0) == 100.0
    assert engine.calculate_risk_score(0.5) == 50.0


def test_calculate_confidence_score_extremes(engine):
    assert engine.calculate_confidence_score(0.5) == 0.0  # maximally ambiguous
    assert engine.calculate_confidence_score(0.0) == 100.0
    assert engine.calculate_confidence_score(1.0) == 100.0


def test_assign_risk_tier_matches_threshold_config(engine):
    assert engine.assign_risk_tier(0.05) == "Low Risk"
    assert engine.assign_risk_tier(0.9) == "Very High Risk"


def test_recommend_lending_action(engine):
    assert engine.recommend_lending_action("Low Risk") == "Approve"
    assert engine.recommend_lending_action("Very High Risk") == "Decline"


def test_recommend_interest_rate_low_risk_below_base(engine):
    rate = engine.recommend_interest_rate("Low Risk", base_rate=10.0)
    assert rate < 10.0


def test_recommend_interest_rate_high_risk_above_base(engine):
    rate = engine.recommend_interest_rate("Very High Risk", base_rate=10.0)
    assert rate > 10.0


def test_recommend_loan_grade_returns_valid_letter(engine):
    grade = engine.recommend_loan_grade(0.05)
    assert grade in {"A", "B", "C", "D", "E", "F", "G"}


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def test_generate_prediction_summary_single_row(engine, splits):
    _, _, X_test, _, _, _ = splits
    summary = engine.generate_prediction_summary(X_test.iloc[[0]])
    assert 0.0 <= summary.default_probability <= 1.0
    assert 0.0 <= summary.risk_score <= 100.0
    assert summary.risk_tier in {"Low Risk", "Moderate Risk", "High Risk", "Very High Risk"}
    assert isinstance(summary.recommended_interest_rate, float)


def test_generate_prediction_summary_rejects_multi_row(engine, splits):
    _, _, X_test, _, _, _ = splits
    with pytest.raises(ValueError):
        engine.generate_prediction_summary(X_test.head(2))


def test_prediction_summary_to_dict(engine, splits):
    _, _, X_test, _, _, _ = splits
    summary = engine.generate_prediction_summary(X_test.iloc[[0]])
    d = summary.to_dict()
    assert "risk_tier" in d and "default_probability" in d


def test_generate_batch_summary_shape(engine, splits):
    _, _, X_test, _, _, _ = splits
    batch = engine.generate_batch_summary(X_test.head(10))
    assert len(batch) == 10
    assert "risk_tier" in batch.columns
    assert list(batch.index) == list(X_test.head(10).index)


def test_export_prediction_report(engine, splits):
    _, _, X_test, _, _, _ = splits
    report = engine.export_prediction_report(X_test.iloc[[0]])
    md = report.to_markdown()
    assert "Risk Assessment" in md
    assert "Recommendation" in md


# ---------------------------------------------------------------------------
# Threshold-config injection
# ---------------------------------------------------------------------------


def test_custom_threshold_config_changes_tier_assignment(quick_pipeline):
    from src.configurable_thresholds import RiskTierBoundary, LendingActionRule, LoanGradeBand

    custom = RiskThresholdConfig(
        risk_tiers=[
            RiskTierBoundary("Low Risk", 0.0, 0.99, "everything is low risk"),
            RiskTierBoundary("Very High Risk", 0.99, 1.01, "almost nothing"),
        ],
        lending_actions=[
            LendingActionRule("Low Risk", "Approve", "d"),
            LendingActionRule("Very High Risk", "Decline", "d"),
        ],
        interest_rate_adjustment_bps={"Low Risk": 0.0, "Very High Risk": 500.0},
        loan_grade_bands=[LoanGradeBand("A", 0.0, 1.01)],
    )
    engine = RiskScoringEngine(model_key="logistic_regression", pipeline=quick_pipeline, threshold_config=custom)
    assert engine.assign_risk_tier(0.5) == "Low Risk"  # would be High/Moderate under defaults


# ---------------------------------------------------------------------------
# Expanded threshold analysis
# ---------------------------------------------------------------------------


def test_expand_threshold_analysis_has_new_columns():
    rng = np.random.default_rng(0)
    y_true = rng.integers(0, 2, 200)
    y_proba = rng.uniform(0, 1, 200)
    table = expand_threshold_analysis(y_true, y_proba, thresholds=[0.2, 0.5, 0.8])
    assert {"approval_rate", "false_positive_rate", "false_negative_rate"} <= set(table.columns)
    assert (table["approval_rate"] >= 0).all() and (table["approval_rate"] <= 1).all()


def test_expand_threshold_analysis_approval_rate_decreases_with_threshold():
    rng = np.random.default_rng(0)
    y_true = rng.integers(0, 2, 300)
    y_proba = rng.uniform(0, 1, 300)
    table = expand_threshold_analysis(y_true, y_proba, thresholds=[0.1, 0.5, 0.9])
    approval_rates = table.sort_values("threshold")["approval_rate"].tolist()
    assert approval_rates[0] <= approval_rates[1] <= approval_rates[2]


def test_plot_expanded_threshold_analysis_runs():
    rng = np.random.default_rng(0)
    y_true = rng.integers(0, 2, 100)
    y_proba = rng.uniform(0, 1, 100)
    table = expand_threshold_analysis(y_true, y_proba, thresholds=[0.2, 0.5, 0.8])
    fig = plot_expanded_threshold_analysis(table, recommended_threshold=0.5, model_display_name="Test Model")
    assert fig is not None
